#!/usr/bin/env bash

# Run MassScan over multiple SLHA templates

for template in suspect2_input/suspect2_lha_*; do
    # Set output folder
    folder=test09/${template##*/}
    # Create folder (for logfile)
    mkdir -p "${folder}"
    # Copy template file
    cp "${template}" suspect2_lha.template
    # Replace output folder in scan.py
    sed -i "s#.*set_directory.*#    PLOTS.set_directory(\"${folder}\")#" scan.py
    ./run_scan 2>&1 | tee "${folder}/log.out"
done
